### ISSUE TITLE
Django 1.7 Support

### ISSUE THREAD

**Issue by macropin** [arthanson/django-genericadmin#22]
Django 1.7 is not supported.

**Comment by murdav** [comment]
Hello,

I was checking right now and the bug is still on PyPi. Please, could someone update the repo?
Thanks!

D

**Comment by mfcovington** [comment]
Hi @jschrewe, now that there is Django 1.7 support, will the version on PyPI be updated soon? Also, are there still plans to hand off the project to @macropin or do you have sufficient time to maintain it? (Not sure which fork I should be paying more attention to.) Thanks!

**Comment by auvipy** [comment]
@macropin @jschrewe I would also love to collaborate on the process

**Comment by mfcovington** [comment]
@auvipy @macropin @jschrewe Count me in!

**Comment by macropin** [comment]
My current interest in this project has dwindled. I also don't have sufficient time to maintain it. I suggest that in order to keep it alive someone forks the repo, and rerelease it under genericadmin *ng* or *redux* or whatever.

**Comment by auvipy** [comment]
@macropin just allow collaborator in the repo.

**Comment by mfcovington** [comment]
Yes, if @jschrewe added a collaborator(s), that could solve the issue.

**Comment by macropin** [comment]
PyPi access also needs to be handed over.

**Comment by auvipy** [comment]
yep

**Comment by arthanson** [comment]
django 1.7 support added
