### ISSUE TITLE
This project is unmaintained

### ISSUE THREAD

**Issue by macropin** [arthanson/django-genericadmin#24]
This project is unmaintained and emails to the [author](mailto:jan@schafproductions.com) bounce.

**Comment by psychok7** [comment]
@macropin thanks i am using your fork for django 1.7 and its working.

**Comment by auvipy** [comment]
add 1.8 support then

**Comment by murdav** [comment]
Yes, it will be great to have 1.8 support.

**Comment by blag** [comment]
This project isn't completely unmaintained, as there's [merged PRs from June 3rd, 2015](https://github.com/jschrewe/django-genericadmin/commits/master).

Django 1.8 support can be found in PR #27. Testing and feedback is appreciated.

**Comment by arthanson** [comment]
Took this project over so it is no longer unmaintained.
