### ISSUE TITLE
django 1.8, 1.9 support and remove support less then 1.7

### ISSUE THREAD

**Issue by auvipy** [arthanson/django-genericadmin#30]

**Comment by cho-is** [comment]
+1

**Comment by murdav** [comment]
+2

**Comment by yoso2010** [comment]
+3 django 1.9 support

**Comment by tammyalexandra** [comment]
+4 django 1.9 support

**Comment by murdav** [comment]
Dear @arthanson,
As far as I remember @jschrewe was taking care of this project, @macropin was the next for a short amount of time and in this https://github.com/arthanson/django-genericadmin/issues/24 you took it. First of all thanks for your effort, but please there are open pull requests from May 15, could you be so kind to intervene?

Thanks again,

Davide

**Comment by arthanson** [comment]
Yes, sorry moving houses and work got in the way for a bit.

**Comment by arthanson** [comment]
merged pull requests to address this.
