### ISSUE TITLE
Django 4.2 Support

### ISSUE THREAD

**Issue by yadomkar** [arthanson/django-genericadmin#56]
Hi @arthanson 👋,

I'm actively upgrading a project from Django 1.10 to Django 4.2 and this library plays an integral role in it. 

🤔 **Question**: Is this library still under active maintenance?

✨ **Proposal**: If so, I'm eager to contribute and help in implementing the necessary adaptations to ensure seamless compatibility with Django 4.2. 

This update will not only benefit my project but also the broader community, as I'm sure others could find themselves in similar situations.

Would love to hear your thoughts! 💭

Thanks!

**Comment by arthanson** [comment]
@yadomkar Django improved their GFK admin support so this library is no longer really needed since about Django 3 or so.  When you update you can remove this library and just use the Django built in GFK widget.

**Comment by darkpixel** [comment]
AI doesn't seem to think so:
```
The django-genericadmin package improves the admin interface for models with GenericForeignKey fields by adding JavaScript-based enhancements to make the ContentType and object selection process more seamless.
Features:
Automatically detects GenericForeignKey fields and provides a better UI.

Replaces the default ContentType dropdown and object_id input with a more integrated picker.

Supports inline admin classes (GenericTabularInline and GenericStackedInline) for polymorphic relationships.

Allows customization of which ContentType fields to use via the generic_fk_fields attribute.
```

...and Django doesn't appear to have improved their "picker" for GenericForeignKeys in admin.
